version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: taskboard-postgres
    restart: always
    environment:
      POSTGRES_DB: taskboard
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: